### ISSUE TITLE
Build job runs even if previous steps fail

### ISSUE THREAD

**Issue by classic-paul** [ocellicode/gpyt-eventclient#5]
Use snippet to prevent release if any previous stage fails
```
  job:
    runs-on: ubuntu-latest
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    needs: [dep1, dep2]
```
